apiVersion: v1
kind: Secret
metadata:
  name: milos-influxdb
  namespace: default
type: Opaque
stringData:
  username: admin
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: milos-grafana
  namespace: default
type: Opaque
stringData:
  username: admin
  password: password
---
apiVersion: metrics.dellemc.com/v1alpha1
kind: InfluxDB
metadata:
  name: milos
  namespace: default
spec:
  adminSecretName: milos-influxdb
  databaseVolumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: nfs
    resources:
      requests:
        storage: 200Gi
---
apiVersion: metrics.dellemc.com/v1alpha1
kind: Grafana
metadata:
  name: milos
  namespace: default
spec:
  ingress:
    fullname: milos
    serviceAccountName: milos-grafana
  influxDBRef:
    name: milos
  adminSecretName: milos-grafana
---
apiVersion: metrics.dellemc.com/v1alpha1
kind: InfluxDBDatabase
metadata:
  name: milos
  namespace: default
spec:
  influxDBRef:
    name: milos
